name: Deploy WasmJS App to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch
  workflow_dispatch:  # Allow manual triggering

permissions:
  contents: read  # Required to fetch the repository content
  pages: write    # Allow deployment to GitHub Pages
  id-token: write # Required by actions/configure-pages

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      
      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build WasmJS App
        run: ./gradlew :composeApp:wasmJsBrowserDistribution

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./composeApp/build/dist/wasmJs/productionExecutable

      # 7. Deploy to GitHub Pages
      - name: "Deploy to GitHub Pages"
        id: deployment
        uses: actions/deploy-pages@v4
